//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RadNotepad.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_LINE               101
#define IDS_FILE_REVERT                 102
#define IDS_TAB_MENU                    103
#define IDS_SEARCH_NOT_FOUND            104
#define IDS_TOOLBAR_SEARCH              105
#define IDR_POPUP_EDIT                  119
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_RadNotepadTYPE              130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES_RESET             152
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_CLASS_VIEW                  163
#define IDI_OUTPUT_WND                  165
#define IDI_PROPERTIES_WND              167
#define IDR_EXPLORER                    169
#define IDR_SORT                        171
#define IDR_POPUP_SORT                  173
#define IDB_CLASS_VIEW                  177
#define IDR_MENU_IMAGES                 179
#define IDR_TOOL_FIELDS                 179
#define ID_TOOLS_MACRO                  181
#define IDR_POPUP_OUTPUT                182
#define IDR_PROPERTIES                  183
#define IDS_EDIT_MENU                   306
#define IDD_GOTOLINE                    310
#define IDR_SCHEME_MASTER               312
#define IDR_EXTMAP                      314
#define IDD_SAVE_MODIFIED               317
#define IDR_OUTPUT                      320
#define IDR_POPUP_TAB                   321
#define IDB_USER_IMAGES                 322
#define IDR_SEARCH                      326
#define IDC_LINE                        1000
#define IDC_LIST1                       1000
#define ID_VERSION                      1001
#define ID_COPYRIGHT                    1002
#define ID_VERSION_SCINTILLA            1003
#define ID_COPYRIGHT_SCINTILLA          1004
#define ID_FILE_REVERT                  32784
#define ID_FILE_CLOSEALL                32788
#define ID_FILE_SAVEALL                 32789
#define ID_VIEW_WHITESPACE              32790
#define ID_VIEW_ENDOFLINE               32791
#define ID_VIEW_WORDWRAP                32792
#define ID_VIEW_USETABS                 32793
#define ID_EDIT_TOGGLEBOOKMARK          32794
#define ID_EDIT_PREVIOUSBOOKMARK        32798
#define ID_EDIT_NEXTBOOKMARK            32799
#define ID_LINEENDINGS_WINDOWS          32804
#define ID_LINEENDINGS_MAC              32805
#define ID_LINEENDINGS_UNIX             32806
#define IDS_CONVERTLINEENDINGS          32807
#define ID_EDIT_MAKEUPPERCASE           32808
#define ID_EDIT_MAKELOWERCASE           32809
#define ID_EDIT_GOTOLINE                32815
#define ID_FILE_READONLY                32816
#define ID_ENCODING_ANSI                32818
#define ID_ENCODING_UTF16LE             32819
#define ID_ENCODING_UTF16BE             32820
#define ID_ENCODING_UTF8                32821
#define ID_EDIT_FINDPREVIOUS            32822
#define ID_EDIT_FINDNEXTCURRENTWORD     32825
#define ID_EDIT_FINDPREVIOUSCURRENTWORD 32826
#define ID_EDIT_FINDMATCHINGBRACE       32831
#define ID_VIEW_SCHEMENONE              32837
#define ID_VIEW_DOCKINGWINDOWS          32838
#define ID_SYNC                         32846
#define ID_EDIT_RENAME                  32848
#define ID_EDIT_VIEW                    32852
#define ID_MARGINS_1                    32856
#define ID_MARGINS_2                    32857
#define ID_MARGINS_3                    32858
#define ID_MARGINS_4                    32859
#define ID_MARGINS_5                    32860
#define ID_VIEW_RETURN                  32861
#define ID_FILE_CLOSEOTHERS             32868
#define ID_FIELD_FILE                   32869
#define ID_FIELD_PATH                   32870
#define ID_FIELD_SELECTED               32871
#define ID_TOOLS                        32872
#define ID_VIEW_SAVESETTINGSONEXIT      32873
#define ID_BUTTON32874                  32874
#define ID_POPUP_WORDWRAP               32875
#define ID_SEARCH_TEXT                  32876
#define ID_SEARCH_PREV                  32878
#define ID_SEARCH_NEXT                  32879
#define ID_SEARCH_INCREMENTAL           32884
#define ID_BUTTON32896                  32896
#define ID_TOOLS_FIRSTTOOL              33000
#define ID_TOOLS_LASTTOOL               33099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32897
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
