#define IDD_SCINTILLA_FINDDLGORD        101
#define IDD_SCINTILLA_REPLACEDLGORD     102
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 1130
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 1131
#define IDC_REGULAR_EXPRESSION          1045
#define IDP_FAIL_SCINTILLA_DOCUMENT_TOO_LARGE 1046
#define IDP_FAIL_SCINTILLA_CREATE_ILOADER 1047
#define IDP_FAIL_SCINTILLA_ADDDATA_DURING_LOAD 1048
