#define IDD_SCINTILLA_FINDDLGORD        101
#define IDD_SCINTILLA_REPLACEDLGORD     102
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 1130
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 1131
#define IDC_REGULAR_EXPRESSION          1045
